apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    run: weather-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    run: weather-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: weather-app
  template:
    metadata:
      labels:
        run: weather-app
    spec:
      containers:
      - name: weather
        image: maayanmi/weather:2.0.3
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /app/history
            name: history-volume
      volumes:
        - name: history-volume
          persistentVolumeClaim:
            claimName: host-pvc